stages:
  - build
  - test
  - qodana

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  # QODANA_TOKEN задаётся в настройках GitLab CI/CD, а не в файле:
  # QODANA_TOKEN: $QODANA_TOKEN

# Общий before_script для runner'а, работающего под Windows (PowerShell)
before_script:
  - echo "Setting JAVA_HOME for GitLab Runner"
  - $env:JAVA_HOME="C:\Program Files\Eclipse Adoptium\jdk-17.0.14.7-hotspot"
  - $env:Path="$env:JAVA_HOME\bin;$env:Path"
  - java -version

build:
  stage: build
  script:
    - cd WiredSpace-API
    - ./gradlew.bat assemble

test:
  stage: test
  script:
    - cd WiredSpace-API
    - ./gradlew.bat test

qodana:
  stage: qodana
  image:
    name: jetbrains/qodana-jvm
    entrypoint: [""]
  only:
    - main
    - merge_requests
  script:
    - qodana --save-report --results-dir=$CI_PROJECT_DIR/.qodana
